### ISSUE TITLE
unclosed file in top level when opening semiology dictionary?

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#106]
e.g. when running test_toplevel_query_lat() and test_toplevel_aphasia_parentheses_and_caps()

`
ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Users\\ali_m\\AnacondaProjects\\PhD\\Semiology-Visualisation-Tool\\resources\\semiology_dictionary.yaml' mode='r' encoding='cp1252'>
  open(semiology_dict_path), Loader=yaml.BaseLoader)  # yaml file
`

**Comment by fepegar** [comment]
Is that the whole traceback?

The problem seems to be in line 82 of QUERY_SEMIOLOGY. Why am I assigned to this?

**Comment by thenineteen** [comment]
thanks I thought it was query_semio...

**Comment by thenineteen** [comment]
actually, 28th March 2020 you changed the code on that line

**Comment by thenineteen** [comment]
ah don't worry, I just read up on it

**Comment by fepegar** [comment]
You already had the `open`. I added the loader to remove a warning, IIRC.

https://github.com/thenineteen/Semiology-Visualisation-Tool/commit/26aa4bf0dcec1d6629b63f49c0cebebfd8224ffa#diff-5b479a83fe8b222974c41a0000c54860L92

**Comment by thenineteen** [comment]
easy fix 3e94614fa9104e4d8e647d03a5e398e968d05b7e
