### ISSUE TITLE
GUI user friendly layout: integrate postictal queries

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#109]
1. 

- [x]  The GUI text box should appear either as a separate popout window to type in (then the semiology added to the list of Semiologies) or it should come up at the top (not at the bottom) 

![GUI text box](https://user-images.githubusercontent.com/10786099/85806039-e45abe00-b745-11ea-93fc-251ee1829547.jpg)

2. Under `settings`, there are currently three tabs. 
- [x] 2.1 The first tab should be  ` "Patient Query" ` and this tab should have the `Dominant hemisphere` options and `Semiologies` in one place (both are patient attributes).  

- [x] 2.1.2 `postictal` inclusion should be an extra option for each semiology specified in a text file (like the "neutral also" .txt file under resources. i.e. by default all semiology should exclude postictal (from the exclusions module)

- [x] 2.2 The second tab should be ` "Database" ` and include the 6 checkboxes from `Epiletogenic zone ground truth` and `Publications approaches`. 
This tab should also have an `qt.QGroupBox('Age')` with a `Paediatric under 7yrs` checkbox. When unticked, it should run `exclude_paediatric_cases()` in the `exclusions module`. 

- [x]  2.3 The third tab should be "Visualisation" as it currently is, but also include the single option of `Auto-update` which is currently sitting in its own tab called `Module`. And also include the default ticked checkbox from #76 (granular visualisation or postcode/hierarchy reversal filter) 

- [ ] 2.4 The fourth tab should be "Advanced Options" and include scaling etc as detailed in #19 

3. The `Data Probe` Menu bottom left needs to go

**Comment by fepegar** [comment]
> The GUI text box should appear either as a separate popout window to type in (then the semiology added to the list of Semiologies) or it should come up at the top (not at the bottom)

I can probably make the first option happen.

> Under settings, there are currently three tabs

In that case, maybe the "Settings" collapsible button should disappear and we can convert everything to tabs.

> The Data Probe Menu bottom left needs to go

It's not part of the module, it's always there. If you don't like/use it, I can tell you how to make it go away in your installation. I use it all the time.

**Comment by thenineteen** [comment]
note also a paediatric exclusions in 2.2

**Comment by fepegar** [comment]
Should the paediatric inclusion check box be ticked by default?

**Comment by thenineteen** [comment]
> Should the paediatric inclusion check box be checked by default?

If it is an inclusion checkbox like the other checkboxes, then by default it should NOT be checked. This is because there is good clinical evidence that seizure semiology of children are significantly different to adults, and the cut off is around 7 yrs hence the use of 7yrs in the description of what we mean by paediatric cases (normally paediatric means <18yrs or variably clinically <16yrs due to Gillick competenece

**Comment by fepegar** [comment]
Ok, thanks for the explanation.

**Comment by thenineteen** [comment]
also where is the issue to include postictal semiology? can't find it. need to integrate into above but I'm sure there was an issue about it already

**Comment by fepegar** [comment]
This one? https://github.com/thenineteen/Semiology-Visualisation-Tool/issues/21

**Comment by thenineteen** [comment]
> This one? #21

yes - the postictal semiology option seems to not have been drowned out in that issue discussion

**Comment by fepegar** [comment]
Still not sure how you'd like the post-ictal option. Should there be one check box per semiology? Why do we need an external text file if the exclusion should happen by default?

**Comment by thenineteen** [comment]
the text file is to determine which semiologies need a "post ictal" option to be included as a checkbox or drop down or some other manner

**Comment by thenineteen** [comment]
this is great work @fepegar the more I use it the more I like the new layout.

We should catch up on the postictals to see the best way forward if it still isn't clear.

**Comment by fepegar** [comment]
Currently, postictals are excluded by default. Would the ticked checkbox mean "include only postictals" or "don't exclude postictals"?

**Comment by thenineteen** [comment]
mutually exclusive, so either "only include postictals" or "exclude postictals (by deafult)"

**Comment by thenineteen** [comment]
NBatm these are some of the post-ictal semiologies in the database:
- nose-wiping
- manual automatisms
- dysphasia
- aphasia
- Todd's paresis/paralysis (no existing semiology for this yet unless we consider it a special case of atonic...TBC)

**Comment by thenineteen** [comment]
I think I'll create new semiologies with the above postictals in the YAML file (SemioDict). I'll then also add a .txt file in resources to determine postictal only semiologies. Soemhow we then need to undo the postictal exclusions for these.

**Comment by thenineteen** [comment]
this commit provides the postictal support a9a163c135243ae7c

**Comment by thenineteen** [comment]
> * [x]  I think I'll create new semiologies with the above postictals in the YAML file (SemioDict).
> * [x]  I'll then also add two .txt files underresources to determine postictal only semiologies for neutral_only and neutral_also.
> * [ ]  We now need to undo the postictal exclusions for these. using `self.include_only_postictal_cases=True` in `semiology.py` for all semiology query terms which include the word "postictal" in them. @fepegar
>   e.g.
> 
> ```python
> pseudocode:
> 
> postictal_semio = r'(?i)' + 'postictal'
> # use either re.search() or postictal_semio in
> if postictal_semio in self.term:
>     self.include_only_paediatric_cases=True
> ```
> 
> Alternatively, for each semiology in the following two text files: `resources_dir / 'semiologies_postictalsonly_neutral_only.txt'` and `semiologies_postictalsonly_neutral_also.txt` we include only postictal cases `self.include_only_postictal_cases=True`
> 
> NB
> I'm excluding
> 
> * `postictal confusion` and
> * `postictal amnesia`
>   which do exist in the database but only only few studies reported these



Use either method above (regex or the .txt files provided) to determine which semiologies should `include_only_postictal_cases=True` and at the same time `include_postictals=True`, by adding an argument to `semiology.py`

```python
class Semiology:
    def __init__(
            self,
            term: str,
            ...
            include_only_postictal_cases: bool = False,
            include_postictals: bool = False,
            ...
            ):
        ...
        self.include_only_postictals = include_only_postictal_cases
        self.include_postictals = include_postictals


...
...

...

    def remove_exclusions(self, df: pd.DataFrame) -> pd.DataFrame:
        ...
        if not self.include_postictals:
                df = exclude_postictals(df)
        if self.include_only_postictals:
                df = only_postictal_cases(df)
```


to double check, either one of `self.include_postictals` or `self.include_only_postictals` should be True (i.e. never both False at the same time)

or both functions can be merged to make a single more coherent one

**Comment by fepegar** [comment]
Can you please summarize what needs to be done? Ideally in a new issue.

**Comment by thenineteen** [comment]
literally just the very last post is relevant here

**Comment by fepegar** [comment]
I understand, but it's still not clear to me what you'd like to have.
