### ISSUE TITLE
Show number of data points for each semiology in the table

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#111]
Rachel suggested this, and I think it's a good idea.

For each semiology, a column can be added to the table showing the raw numbers for each structure.

**Comment by thenineteen** [comment]
related to pull request #108 as returns the stats

**Comment by fepegar** [comment]
Hmm I meant showing the data frame returned by `semiology.get_df_from_semiologies`, i.e. before normalising and combining.

**Comment by thenineteen** [comment]
Is this for semiology combinations only? I thought you meant next to the checkboxes

**Comment by fepegar** [comment]
I'll implement it and upload a figure here to show what I mean.

**Comment by fepegar** [comment]
Voilà:

<img width="1280" alt="Screen Shot 2020-06-28 at 17 00 22" src="https://user-images.githubusercontent.com/12688084/85952399-eea4d400-b960-11ea-8e49-77dc6f5d7396.png">

@neurokleos

**Comment by fepegar** [comment]
I'll merge this now, as well as the paediatric filter. We can revert stuff later if necessary.

**Comment by thenineteen** [comment]
cool.

just an improvement: don't do this for single semiologies. 

![image](https://user-images.githubusercontent.com/10786099/85953995-37ae5580-b96c-11ea-9726-ae1e92310f70.png)

**Comment by fepegar** [comment]
Done in 9922a1b.
