### ISSUE TITLE
Semiologies checkboxes can disappear and be impossible to pull down again

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#114]
generally there is very tight space to work with the semiology input and seeing the table of scores. Is there a way to epxand and pop-out these as full screen windows?

**Comment by fepegar** [comment]
Yes, there is a little button at the top of the module that you can use to pop out the module widget. But the layout might change after refactoring the GUI (#109).

**Comment by fepegar** [comment]
Does this still happen?

**Comment by thenineteen** [comment]
nope! good job. I like the new layout much better
