### ISSUE TITLE
test_dummy_data_hierarchy is failing

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#115]
This happens after setting `granular=True` by default in `Semiology`.

**Comment by thenineteen** [comment]
the test in Class TestDummyDataDummyDictionary fails because of the change in default behaviour

The tests in Class TestDummyDataHierarchyReversal fail because of the same issue. Can ignore for now until I update the assertions - won't have time yet

**Comment by thenineteen** [comment]
alternative: change default behaviour back

**Comment by fepegar** [comment]
I thought the default behaviour is the one that ensures a reliable output.

**Comment by thenineteen** [comment]
yes so let's just leave it and I will fix later

**Comment by thenineteen** [comment]
c161a1d498f4108dbd2d6e91f3d5366035b154a8
