### ISSUE TITLE
Modify paediatric filter under 7 yrs

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#119]
Instead of excluding or including paediatric data under 7yrs, make the checkbox switch between paediatric under 7yrs and non paediatric over 7yrs (so never including both semiologies).

**Comment by thenineteen** [comment]
this was a major undetected bug until my new test
`test_paed_exclusions_query_semio`

until now, excluding paediatric cases with `exclude_paediatric_cases()` was actually excluding anything with either a y or a n and keeping the NaNs/nulls.

**Comment by thenineteen** [comment]
bug fixed in 0211f14aa288d309ad99851c967d290d56e6ca07

**Comment by thenineteen** [comment]
@fepegar please can the checkbox have a tooltip?

`Exclude all cases for which we are certain that the semiology was reported in a patient under 7-years old`

**Comment by thenineteen** [comment]
also @fepegar :

is it possible to modify the SemiologyVisualisation.py so that 

1. No change in this part: as it is currently, the paediatric checkbox remains unticked by deafult and this does the same thing it currently does (i.e. sets `paediatricCheckBox.isChecked()` to `False` and `include_paediatric_cases` to `False` and so runs `exclude_paediatric_cases`)

2. if and when the check box is ticked, it now runs `only_paediatric_cases()` from `exclusions.py`?

**Comment by fepegar** [comment]
The checkbox should mean "include", not "exclude". So the tooltip should probably say "Include..."

But if it's ticked, why should it include only paediatric cases?

Also, it says `padeiatric` in `only_paediatric_cases`.

**Comment by thenineteen** [comment]
> So the tooltip should probably say "Include..."

perfectly agree! thanks

**Comment by thenineteen** [comment]
> But if it's ticked, why should it include only paediatric cases?

because it would mean a paediatrician or paediatric epileptologist is querying the database. As mentioned elsewhere, the semiology of adults and children under 7 are very different due to differential brain maturity and functon.

**Comment by thenineteen** [comment]
> Also, it says `padeiatric` in `only_paediatric_cases`.

it does indeed good spot. This is a propagated typo which exists in the database so won't fix for now.

**Comment by thenineteen** [comment]
I think this can be closed?
