### ISSUE TITLE
ictal speech modify

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#120]
- [ ] @neurokleos `ictal speech retention` needs to be removed from the database (it implies normal speech, not ictal speech). Please comment here to confirm once this is done, thanks :) if you also think it should remain as they mean ictal speech, then please change this in the category label

in the following publication:

`Rodriguez AJ, Buechler RD, Lahr BD, So EL. Temporal lobe seizure semiology during wakefulness and sleep. Epilepsy Res 2007; 74(2-3): 211-4.`

- [x] @thenineteen need to modify the regex to exclude ictal speech arrest and ictal speech impairment

**Comment by thenineteen** [comment]
ictal speech regex corrected in 1a8dbda466067d59cf42f6ba8894266cfef455de

**Comment by thenineteen** [comment]
note also that the current database only has data up to first author letter `K` so no ictal speeches except for coprolalia

**Comment by neurokleos** [comment]
In this very paper, this was reported as "semiology" by the author, but I wanted to discuss this point with you and JD (and we did), as this is related to the ictal testing, more than to spontaneous semiology. So yes, as agreed, let's remove it.

**Comment by thenineteen** [comment]
Thanks.

once done, can you please tick the box so we know it's done

**Comment by neurokleos** [comment]
done
