### ISSUE TITLE
do not enter decimal places for lateralising and localising

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#125]
Please stick to integers for SemioBrain Database

@neurokleos

**Comment by thenineteen** [comment]
I have reversed all the decimals in the live database

the ones I changes include:

Sheet | Cell | Value
-- | -- | --
Main | P198 | 3.5
Main | R198 | 3.5
Main | S198 | 3.5
Main | F609 | sEEG and post-op sz free for 2.5 y
Main | F1450 | post-op Engel Ia 3.6yrs, 3.9, 3.5, 3.1 yrs
Main | D1531 | sudden, brief, 1.5- to 30-s periods of feeling generalized discomfort, during which he appeared startled, confused, and tense with face flushed and eyes wide opened, with and without brief loss of awareness.
Main | Q1543 | MRI: FCD/L dorsolateral premotor cortex (SFG, MFG & superior bank of the IFG), next to the preCG resections: 1st surgery: L dorsolateral premotor corticectomy up to the preCG/25 months 2nd surgery: L dorsolateral premotor (SFG‐MFG) and mesial premotor (SMA) corticectomy (EZ defined by SEEG)/8.5 years
Main | Q1544 | MRI: FCD/L dorsolateral premotor cortex (SFG, MFG & superior bank of the IFG), next to the preCG resections: 1st surgery: L dorsolateral premotor corticectomy up to the preCG/25 months 2nd surgery: L dorsolateral premotor (SFG‐MFG) and mesial premotor (SMA) corticectomy (EZ defined by SEEG)/8.5 years
Main | Q1545 | MRI: FCD/L dorsolateral premotor cortex (SFG, MFG & superior bank of the IFG), next to the preCG resections: 1st surgery: L dorsolateral premotor corticectomy up to the preCG/25 months 2nd surgery: L dorsolateral premotor (SFG‐MFG) and mesial premotor (SMA) corticectomy (EZ defined by SEEG)/8.5 years
Main | P1801 | 194.5
Main | R1801 | 194.5
Main | S1801 | 194.5
Main | AA1801 | 194.5
Main | AH1801 | 194.5
Main | P1803 | 124.5
Main | R1803 | 124.5
Main | S1803 | 124.5
Main | AA1803 | 124.5
Main | AH1803 | 124.5
Main | P1805 | 54.5
Main | R1805 | 54.5
Main | S1805 | 54.5
Main | AA1805 | 54.5
Main | AH1805 | 54.5
Main | P1810 | 19.5
Main | R1810 | 19.5
Main | S1810 | 19.5
Main | AA1810 | 19.5
Main | AH1810 | 19.5
Main | P1819 | 5.5
Main | R1819 | 5.5
Main | AA1819 | 5.5
Main | P1835 | 303.5
Main | R1835 | 303.5
Main | S1835 | 303.5
Main | AA1835 | 303.5
Main | J1836 | 159.5
Main | O1836 | 159.5
Main | P1836 | 159.5
Main | R1836 | 159.5
Main | S1836 | 159.5
Main | AA1836 | 159.5
Main | Q1925 | F 56.5% (13) ; T 37% (10)
Main | J1928 | 25.5
Main | P1928 | 25.5
Main | Q1928 | F 41.7% (9.5) (latency 11s (1-52s)); T 59.3% (16) (latency 16s (1-38s))
Main | AL1928 | 9.5
Main | P1931 | 18.5
Main | Q1931 | F 37.5% (8.5) (latency 8s (1—38s) ); T 37% (10) (latency 12s (2—25s))
Main | AL1931 | 8.5
Main | Q1934 | F 43.5% (10) (latency 17s (1—34s)); T 33.3% (9) (latency 20s (3—53s))
Main | Q1940 | F 5.9% (1.5) ; T 2% (0.5)
Main | R1940 | 0.5
Main | AL1940 | 1.5
Main | F2289 | post-op sz freedom 1.5y f/u + intracranial EEG (sEEG)
Main | F2290 | post-op sz freedom 1.5y f/u + intracranial EEG (sEEG)
Main | F2291 | post-op sz freedom 1.5y f/u + intracranial EEG (sEEG)
Main | F2295 | post-op sz freedom 1.5y f/u + intracranial EEG (sEEG)
Main | F2296 | post-op sz freedom 1.5y f/u + intracranial EEG (sEEG)
Main | F2297 | post-op sz freedom 1.5y f/u + intracranial EEG (sEEG)
Main | F2298 | post-op sz freedom 1.5y f/u + intracranial EEG (sEEG)
Main | F2299 | post-op sz freedom 1.5y f/u + intracranial EEG (sEEG)
Main | F2300 | post-op sz freedom 1.5y f/u + intracranial EEG (sEEG)
Main | R2648 | 7600.5
Main | AL2648 | 1867.5

**Comment by neurokleos** [comment]
This is another thing we needed to discuss and agree on before taking action - if your remember the 0.5 values come from % converted into absolute numbers. We need to agree on the strategy of how to approximate 0.5 - towards +1 or -1?

**Comment by thenineteen** [comment]
lets say we round it. Usually .5 are rounded up.

**Comment by neurokleos** [comment]
great! I will report this in the prisma protocol in the % data collection strategy

**Comment by thenineteen** [comment]
cool. can we close this issues?
