### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#126]
Because of this: https://github.com/thenineteen/Semiology-Visualisation-Tool/commit/8395a5916a535106096a63056498bcec135e43b2

**Comment by thenineteen** [comment]
It passes on pandas version 1.0.3

could you check your machine pandas version?

see: https://github.com/blue-yonder/tsfresh/issues/485

**Comment by thenineteen** [comment]
actually my bad! not a version issue

I forgot to push the database update!
