### ISSUE TITLE
fix my pytest: ModuleNotFoundError: No module named 'mega_analysis'

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#127]
when I run pytest from base and root of \Semiology-Visualisation-Tool:

===================================================================================================== ERRORS ======================================================================================================
____________________________________________________________________________________ ERROR collecting tests/test_dummy_data.py ____________________________________________________________________________________ 
ImportError while importing test module 'C:\Users\ali_m\AnacondaProjects\PhD\Semiology-Visualisation-Tool\tests\test_dummy_data.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_dummy_data.py:6: in <module>
    from mega_analysis.crosstab.file_paths import file_paths
E   ModuleNotFoundError: No module named 'mega_analysis'
_______________________________________________________________________________ ERROR collecting tests/test_dummy_data_hierarchy.py _______________________________________________________________________________ 
ImportError while importing test module 'C:\Users\ali_m\AnacondaProjects\PhD\Semiology-Visualisation-Tool\tests\test_dummy_data_hierarchy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_dummy_data_hierarchy.py:6: in <module>
    from mega_analysis.crosstab.file_paths import file_paths
E   ModuleNotFoundError: No module named 'mega_analysis'
____________________________________________________________________________________ ERROR collecting tests/test_exclusions.py ____________________________________________________________________________________ 
ImportError while importing test module 'C:\Users\ali_m\AnacondaProjects\PhD\Semiology-Visualisation-Tool\tests\test_exclusions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_exclusions.py:2: in <module>
    from mega_analysis.semiology import mega_analysis_df
E   ModuleNotFoundError: No module named 'mega_analysis'
____________________________________________________________________________________ ERROR collecting tests/test_get_lobes.py _____________________________________________________________________________________ 
ImportError while importing test module 'C:\Users\ali_m\AnacondaProjects\PhD\Semiology-Visualisation-Tool\tests\test_get_lobes.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_get_lobes.py:4: in <module>
    from mega_analysis.crosstab.gif_lobes_from_excel_sheets import \
E   ModuleNotFoundError: No module named 'mega_analysis'
_______________________________________________________________________________ ERROR collecting tests/test_query_lateralisation.py _______________________________________________________________________________ 
ImportError while importing test module 'C:\Users\ali_m\AnacondaProjects\PhD\Semiology-Visualisation-Tool\tests\test_query_lateralisation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_query_lateralisation.py:3: in <module>
    from mega_analysis.semiology import (
E   ModuleNotFoundError: No module named 'mega_analysis'
_________________________________________________________________________________ ERROR collecting tests/test_query_semiology.py __________________________________________________________________________________ 
ImportError while importing test module 'C:\Users\ali_m\AnacondaProjects\PhD\Semiology-Visualisation-Tool\tests\test_query_semiology.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_query_semiology.py:3: in <module>
    from mega_analysis.semiology import (
E   ModuleNotFoundError: No module named 'mega_analysis'

**Comment by fepegar** [comment]
I suggest you open an issue in the `pytest` repo: https://github.com/pytest-dev/pytest

**Comment by thenineteen** [comment]
thanks
