### ISSUE TITLE
Localising Datapoints: counting semiology-level or patient-level localisation?

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#128]
A question arose that when we report localising, is this semiology or patient level. 

**CASE A**
`Oehl B, Brandt A, Fauser S, Bast T, Trippel M, Schulze-Bonhage A. Semiologic aspects of epileptic seizures in 31 patients with hypothalamic hamartoma. Epilepsia 2010; 51(10): 2116-23.`

- [x] 1.  it doesn't include `Total Pt included` - please update?
2. the `Localising` column here, like many other places, shows the number of patients with the semiology. This seems at first glance to be **patient-level** localising.

But in another place like:

**CASE B**
`Mohamed IS, Gibbs SA, Robert M, Bouthillier A, Leroux JM, Khoa Nguyen D. The utility of magnetoencephalography in the presurgical evaluation of refractory insular epilepsy. Epilepsia 2013; 54(11): 1950-9.` we see that 1 patient's multiple semiologies are combined in one row but the localising only has a "1" which suggests localising is counting **patient-level** data.

So is it **patient-level** data? (no... see below)

**Comment by thenineteen** [comment]
The answer is nuanced:

- in **CASE A** above, each patient can have more than one row, so it was not correct to say that this is patient-level. In fact, looking at the total pt included, we can see the sum of localising is greater, so this is still semiology-level

- in **CASE B** each row can be multiplied and extra localising points added, to truly make it semiology-level.


So, the conclusion is: when we sum localising, we are actually getting a number somewhere between # pts and # semiologies. 
with # semiologies > # pts

**Comment by neurokleos** [comment]
I don't understand the issue. These data are  of course patient-based and you can see the total.

**Comment by neurokleos** [comment]
@thenineteen looking at Mohamed's paper (that you screened), I see a major problem regarding semiology category: why did you put multiple semiologies together in one category??

**Comment by neurokleos** [comment]
CASE B is not correct according to my point of you - we can go through a data collection together to clarify things and be on the same page if you wish?

**Comment by thenineteen** [comment]
summing the localising datapoints in Semio2Brain database gives an estimate which lies between semiology-level and patient-level

**Comment by neurokleos** [comment]
1 data-point is 1 patient showing 1 semiology localising to specific regions and/or lateralising.

**Comment by thenineteen** [comment]
This is related to summing the `Localising` column, which does not give a patient level result.

Each patient can have two simultaneous semiologies and both could be entered on a new row in the database. Therefore, the sum is semiology-level not patient level.

But some data entries have multiple semiologies in one row, therefore the true semiology-level datapoints is greater. 

> 1 data-point is 1 patient per semiology localising to specific regions and/or lateralising. Basically patients are assigned to semiology and regions. The numbers per se are always patient-based by definition.
