### ISSUE TITLE
Localising value should not be assigned to Post-ictal semiologies 

### ISSUE THREAD

**Issue by neurokleos** [thenineteen/Semiology-Visualisation-Tool#130]
@thenineteen I know you wanted to test whether post-ictal semiologies might have some sort of localising value, and for this reason (from a certain point of the database) you wanted to collect both loc and lat from post-ictal semiologies. But at the moment all this loc data assigned to post-ictal semio got mixed to the rest, and it is not clear to me whether we can really control for this - the only solution would be filtering out the post-ictal semiologies, but doing this we would loose their lat value, that is the reason why we collected post-ictal semio in the first instance.

**Comment by thenineteen** [comment]
don't worry we can control for everything.

Note also:

1. when we are combining semiologies, we localise the 2nd, 3rd or even last semiology. Why is the postictal semiology any different?

2. In fact, when searching for the combinations of semiologies, as we did, we use this same database which has mainly the initial (or most prominent) semiology. But when searching for the postictal semiology, it will ONLY look at the postictal entries on the database.

3. The control happens using a regular expression looking for all possibilities of post-ictal that we have the SemioBrain excel database

**Comment by thenineteen** [comment]
to summarise concretely:

1. post ictals are already filtered out by default (there is code for this and has been since last year)
2. when combining semiologies in the query, we search for all semiologies irrespective of order, but we treat post ictal as special and it will only match postictals in the database.

**Comment by neurokleos** [comment]
When you say that you filter out post-ictal semiologies with the code, you are also filtering out the lat value? or only the loc value (hopefully)?

**Comment by thenineteen** [comment]
If we have a patient_A with semiologies:
1. dialeptic
2. tonic L arm
3. post ictal aphasia

How do you envisage we search? why would you include localisation for tonic L arm but not post ictal aphasia?

**Comment by neurokleos** [comment]
We discussed this with JD many times, and we agreed to select onlu early onset semio - when chronology is available, plus post-ictal signs that can be helpful to lataleralise the EZ - we know that post-ictal semiologies do not have localising power as is the product of a late network. To reply to your putative case: If tonic L arm follows dialaptic, we would include only dialeptic as early onset semiology for localising.

**Comment by thenineteen** [comment]
@neurokleos data is already collected. I meant for analysis and visualisation.

**Comment by neurokleos** [comment]
I meant for both
