### ISSUE TITLE
3D Slicer hangs if starting while running a second screen - reproducible

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#131]
Reproducible:

start 3D slicer without external monitor. works
connect external monitor and move the 3D slicer app to the external monitor (extended screens)
close 3D slicer app.
Now, when restarting 3D slicer app, it will attempt to open it in the external monitor. It will fail 100%
Windows 10
3D Slicer 4.11.0-2020-05-12 r29055 / 829bbe1

“Not Responding”

**Comment by thenineteen** [comment]
I'm posting this  on the 3D slicer forum on a similar topic from 2017:

https://discourse.slicer.org/t/slicer-crashes-during-loading-error-in-python/1470/16

**Comment by fepegar** [comment]
`wontfix` means that you're not planning to work on this issue: https://docs.github.com/en/github/managing-your-work-on-github/about-labels#using-default-labels

**Comment by thenineteen** [comment]
well we can't really fix this, can we?

**Comment by fepegar** [comment]
But not because we don't want to, but because it's not our issue but Slicer's.
