### ISSUE TITLE
Custom Semiology (Mappings Calibration TLd) returns zero GIFs

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#140]
see below. it shows clearly that some GIFs with zero values are returned. From what I gathered, this is a ghosting effect from the Hierarchy Reversal. Concretely: TLd maps to `STG (includes Transverse Temporal Gyrus, Both Planum)` but also to the hierarchy (postcode system) of `TL` and `Lateral Temporal` which map to all the other regions - then Hierarchy Reversal removes these, and zeros are still returned (e.g. Left Amygdala below):

![image](https://user-images.githubusercontent.com/10786099/86969993-8e830e80-c166-11ea-87b4-4d1ac0b94620.png)

we need to prune these zeros

**Comment by thenineteen** [comment]
I tried fixing this by including the following code

```
query_semiology_result = query_semiology_result.loc[:,
                                                            (query_semiology_result.any(axis=0) != 0)]
```


right after the call to `query_semiology` within `query_lateralisation`. This works to an extent in that it changed the fixture for aphasia in the test `test_toplevel_query_lat_mappings` - only removing the zero entry gifs and keeping the rest intact.

However, it did not change the output of slicer: still had zero GIFs... hmm...

(Furthermore, this may break the code if it removes lateralising column for being all zeros)
So I tried the following, this time still within `semiology.py` but after
```
if ll_empty:
                message = f'No query_semiology results for term "{self.term}"'
                raise ValueError(message)
            else:
```

I added:
```
from mega_analysis.crosstab.semiology_all_localisations import all_localisations
                all_locs = all_localisations()
                loc_cols_present = [
                    col for col in query_semiology_result.columns if col in all_locs]
                query_semiology_result[loc_cols_present].replace(
                    0, np.nan).dropna(axis=1, how='all', inplace=True)
```


this time all tests still pass (which is ominous as the fixture should fail) and the slicer doesn't change behaviour anyway. The solution I think needs to be an amalgamation of the above

The final solution evades me and involves semiology.py (so as to keep current test behaviours intact) so adding slicer label

**Comment by thenineteen** [comment]
maybe @fepegar we can just remove the zero gif parcellations from the `get_num_datapoints_dict() function?`

**Comment by thenineteen** [comment]
this still happens

**Comment by fepegar** [comment]
I can't reproduce: No query_semiology results for term "mappings TLd".

**Comment by thenineteen** [comment]
Yes I'm not surprised you can't reproduce this now actually,  because I had ran this semiology previously in the beta database version - it doesn't exist in the uptodate Database. I was getting this because it was using my local cache by default (Advanced Settings tab).

This has indeed been fixed. Thanks.
