### ISSUE TITLE
Finalise SemioBrain Database Semiology Category Assignments

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#142]
After SemioDict version gets a major increment (#141), finalise the SemioBrain Database assigned semiology categories. 

Major bump in SemioBrain Database version.

**Comment by thenineteen** [comment]
I've closed this as I expect minor changes on discussion with BD/FC given the available data and after reviewing the ILAE Semiology Glossary and papers and updated the SemioDict taxonomy replacement

**Comment by neurokleos** [comment]
Great! Let's freeze this issue until FC and BD discussion. 

Preliminary SemioBrain list:

Aphasia
Aphemia
Astatic
Asymmetric Tonic
Atonic
Auditory
Autonomous-Vegetative
Behavioural Arrest
Blink
Clonic
Cough
Dacrystic
Dialeptic / LOA
Drinking
Dysphasia
Dystonic
Epigastric
Eye Version
Fear-Anxiety
Gelastic
Grimace
Head Turn
Head Version
Hypermotor
Hypomotor
Ictal Limb Paresis
Ictal Pout
Ictal Speech
LOC
Lower Limb Automatism
Myoclonic
Non-specific Aura
Nose-wiping
Olfactory-Gustatory
Oral Automatisms
Other Complex Motor
Psychic
Somatosensory
Spasms - epileptic/infantile
Spitting
Tonic
Tonic-Clonic
Upper Limb Automatism
Vestibular
Visual 
Vocalisation
 

ILAE Glossary-derived list:

 

Abdominal
Akinetic
Affective Experiential
Aphasic
Astatic 
Asymmetric Tonic
Atonic
Auditory Elementary 
Autonomic (Aura)
Autonomic (Seizure)
Cephalic 
Clonic
Dacrystic
Dialeptic
Dyscognitive
Dysphasic
Dyspraxic
Dystonic Posturing
Epileptic Spasm
Eye Blinking
Mimetic Automatism
Mnemonic Experiential
Gelastic 
Gestural Automatism
Gustatory Elementary 
Hallucinatory Experiential
Head Turning
Hyperkinetic 
Hypermotor
Hypersalivation
Hypokinetic 
Hypomotor
Illusory Experiential
Manual Automatism
Myoclonic
Negative Myoclonic
Nystagmus
Olfactory Elementary
Oroalimentary Automatism
Pedal Automatism
Pilomotor
Peri-ictal Water Drinking
Post-ictal Aphasia
Post-ictal Nose-wiping 
Olfactory Elementary
Oroalimentary Automatism
Somatosensory Elementary
Spitting
Todd's Paralysis
Tonic
Tonic-Clonic
Unspecified Aura
Verbal Automatism
Visual Elementary
Vocal Automatism
Vomiting/ Retching

**Comment by neurokleos** [comment]
Ali, please share here (and in reply to JD email) the most recent version of the preliminary SemioBrain list, where you have integrated few semio from ILAE Glossary.

**Comment by thenineteen** [comment]
it is available here 

https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/master/resources/semiology_dictionary.yaml

> Ali, please share here (and in reply to JD email) the most recent version of the preliminary SemioBrain list, where you have integrated few semio from ILAE Glossary.
