### ISSUE TITLE
scores table crops

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#161]
after a query, the scores table is cropped and it is not easy to compare  two structures' scores that are far from each other

![image](https://user-images.githubusercontent.com/10786099/89485055-ceeea000-d797-11ea-9520-0444860daf34.png)

**Comment by fepegar** [comment]
I can't reproduce. It might be a Windows issue. I wouldn't know how to fix it anyway.

<img width="1392" alt="Screen Shot 2020-08-20 at 21 17 11" src="https://user-images.githubusercontent.com/12688084/90821297-9370db80-e32a-11ea-9670-5137f61b0d91.png">
