### ISSUE TITLE
Segmentation not found in scene: MNI_152_gif_cerebrum

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#173]
We have a list of GIF parcellations which seems to include 152, but the logging shows this when e..g running LEFT Tonic semiology

I don't think it is of major concern but just checking, as the next few error messages are also related

**Comment by thenineteen** [comment]
![image](https://user-images.githubusercontent.com/10786099/90629591-8ca57400-e217-11ea-8ef6-b670cc17e3e9.png)

**Comment by fepegar** [comment]
152 is the number of images used to create the ICBM template we're using: http://www.bic.mni.mcgill.ca/ServicesAtlases/ICBM152NLin2009

It's not an error.
