### ISSUE TITLE
Waring the color table node...(.txt) can't be found

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#174]
multiple errors in slicer stating

`Warning: In D:\D\P\Slicer-0\Libs\MRML\Core\vtkMRMLLabelMapVolumeDisplayNode.cxx, line 123
vtkMRMLLabelMapVolumeDisplayNode (000002376FC6B430): vtkMRMLLabelMapVolumeDisplayNode: Warning, the color table node: vtkMRMLColorTableNodeFileGenericColors.txt can't be found`

![image](https://user-images.githubusercontent.com/10786099/90629820-e60da300-e217-11ea-948a-4f49a2c71ed3.png)

**Comment by fepegar** [comment]
These are not errors, nor bugs, nor of our concern.

**Comment by thenineteen** [comment]
how do I suppress them - I'm double checking some debug output variations in vs code vs 3d slicer and these messages drown out some messages

**Comment by fepegar** [comment]
I don't know. You can ask in the Slicer forum.
