### ISSUE TITLE
Pandas SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame.

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#179]
when running a debug script (see comment below), for some semiology terms we get this pandas warning. There is no clue as to where this occurs in the code which makes it difficult to resolve. e.g. when running the terms 

1. - [x] `Automatism - Lower Limb - Non Hypermotor`  or 

2. - [x] `Hypermotor`, or

3. - [x]  `Aphemia`

4. - [x]  `Astatic`

5. - [ ] `Coprolalia`

6. - [ ]  `Cough`

7. - [x] `Dialeptic/LOA`
8. - [ ] `Behavioural Arrest or Akinesis`

the following warning message occurs:

```
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy    
  self.obj[item] = s

```

**Comment by thenineteen** [comment]
this is the debug script:


```python 

import mega_analysis
from mega_analysis import Semiology, Laterality
from pathlib import Path

from mega_analysis.crosstab.file_paths import file_paths
from mega_analysis.crosstab.mega_analysis.MEGA_ANALYSIS import MEGA_ANALYSIS

file = Path(__file__).parent/'resources'/'semiologies_neutral_also.txt'
list_of_terms = list(open(file, 'r'))
for term in list_of_terms:

    patient = Semiology(
        term.strip(),
        symptoms_side=Laterality.LEFT,
        dominant_hemisphere=Laterality.LEFT,
    )

    heatmap = patient.get_num_datapoints_dict()
    print("\nSemiology: ", term)
    print('\nResult:', heatmap, '\n')

```

**Comment by thenineteen** [comment]
any ideas where to find the culprit code (likely to be a line)?

**Comment by fepegar** [comment]
Have you debugged it?

**Comment by thenineteen** [comment]
> Have you debugged it?

that's what I need help with, ideas?

**Comment by fepegar** [comment]
I mean proper debugging with breakpoints etc. in e.g. VS Code.

**Comment by thenineteen** [comment]
> I mean proper debugging with breakpoints etc. in e.g. VS Code.

ongoing

**Comment by fepegar** [comment]
It happens somewhere in QUERY_LATERALISATION for e.g. 'Behavioural Arrest or Akinesis'.

**Comment by fepegar** [comment]
I think in

```python
df.loc[df_of_missing_lats.index, 'Lateralising'] = df_of_missing_lats[[
            'CL', 'IL', 'DomH', 'NonDomH']].sum(axis=1)
```

**Comment by thenineteen** [comment]
thanks I'll have a look!

**Comment by thenineteen** [comment]
> I think in
> 
> ```python
> df.loc[df_of_missing_lats.index, 'Lateralising'] = df_of_missing_lats[[
>             'CL', 'IL', 'DomH', 'NonDomH']].sum(axis=1)
> ```

correcting this did not resolve the issue

**Comment by thenineteen** [comment]
this was interesting as the fix was to copy() the very initial df passe into the functions as an argument.
this changed the behaviour of the test where running exclusions(df) no longer also changed the original df.

I'm still a little bewildered then, given the above, why the other exclusion functions in the `exclusions` module work without explicitly stating `df=df.copy()`

**Comment by thenineteen** [comment]
this warning still occurs e.g. when querying dialeptic/loa with all three GTs but excluding ET/CES. If exclude concordance from the GTs and keep the priors the same, the error doesn't occur.

**Comment by thenineteen** [comment]
```python
patient = Semiology('Dialeptic/LOA',
    symptoms_side=Laterality.LEFT,
    dominant_hemisphere=Laterality.LEFT,
    inverse_localising_values=False,  # default is False
    self.include_cortical_stimulation = False,
    self.include_et_topology_ez = False,
)
```

**Comment by fepegar** [comment]
I do get the warning with that code. What version of pandas are you using? Mine is

```python
In [3]: import pandas

In [4]: pandas.__version__
Out[4]: '1.0.5'
```

**Comment by thenineteen** [comment]
1.0.3

**Comment by fepegar** [comment]
Can you update and try again?

P.S.: I edited your code to make it a MWE.

**Comment by thenineteen** [comment]
I do get the warning in the anaconda cmd prompt... 

![image](https://user-images.githubusercontent.com/10786099/93803779-45a70600-fc3d-11ea-896c-67b318453bbf.png)

**Comment by thenineteen** [comment]
actually, just restarted vs code, I do get the warning now too - but I don't get an error which aborts the calculation
