### ISSUE TITLE
semiology_dict_path should not be defined in QUERY_SEMIOLOGY

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#18]
As discussed on https://github.com/fepegar/EpilepsySemiology/issues/1.

Its value should be passed as an argument from a higher-level function.

**Comment by fepegar** [comment]
Fixed in 8bad0d2cff61b4c294f1fc49ba0b79cbb109cb73.

**Comment by thenineteen** [comment]
thanks
