### ISSUE TITLE
SemiologyVisualisation getLobesMapping limits cerebellar mapping

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#181]
`result['cerebellum'] = [72, 73, 74]` within `SemiologyVisualisation` module:

```python
def getLobesMapping(self):
        from mega_analysis import gif_lobes_from_excel_sheets
        result = {}
        for key, labels in gif_lobes_from_excel_sheets().items():
            lobe = key.split()[1]
            lobe = lobe.lower() if len(lobe) > 2 else lobe
            left_key = f'Left {lobe}'
            right_key = f'Right {lobe}'
            result[left_key] = []
            result[right_key] = []
            for label in labels:
                name = self.getStructureNameFromLabelNumber(label)
                if 'Left' in name:
                    result[left_key].append(label)
                elif 'Right' in name:
                    result[right_key].append(label)

        result['cerebellum'] = [72, 73, 74]
        return result
```

I presume there is a reason for the explicit determination of the cerebellar GIFs? In our Semio2Brain Excel Database the `GIF CEREBELLUM` sheet shows there should be other GIFs:

39, 40, 41 ,42, 72, 73, 74

**Comment by fepegar** [comment]
Yes, those 3 structures are not assigned to left or right hemispheres, so the assignment had to be hard-coded.

**Comment by fepegar** [comment]
The lateral cerebellar structures are correctly assigned. You can run in the Python console: `slicer.semiologyVisualisation.parcellation.colorTable.getLobesMapping()`.
