### ISSUE TITLE
cerebellar vermis isn't visualised despite mapping support

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#187]
GIF #s 72, 73, 74 which are not lateralised, show up in the results table in the GUI but are not shown in the brain heatmap

e.g. see here (produced during manual quality control of every single mapping and localisation label as part of #75, using the branch `Mappings Calibration starting at v 1.1.0` ) :

![image](https://user-images.githubusercontent.com/10786099/91175260-70eb1380-e6d8-11ea-8b7a-451342598b2a.png)

**Comment by thenineteen** [comment]
related to #184 and #181

**Comment by fepegar** [comment]
I think this is the same problem as #184. These structures are not generated by the GIF algorithm.

**Comment by fepegar** [comment]
You could open an issue on https://github.com/KCL-BMEIS/NiftySeg.

**Comment by thenineteen** [comment]
similar to white matter, cerebellar regions not as important, only 10 datapoints from over 13000
