### ISSUE TITLE
PendingDeprecationWarning: Use  'tree.iter()' or 'list(tree.iter())' instead

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#188]
```python
PendingDeprecationWarning: This method will be removed in future versions.  Use 
'tree.iter()' or 'list(tree.iter())' instead.
  for elem in self.tree.iter() if Element_has_iter else self.tree.getiterator():
```

This warning comes up during testing. Similar to #179 I can't find where this occurs during debugging. Any help would be appreciated.

**Comment by thenineteen** [comment]
one function that returns this is:

`all_localisations()`

**Comment by thenineteen** [comment]
@sadeghs how does one go about chasing the functions that result in the above warning? I can't figure what the best debug method is when the call stack doesn't trace this warning

**Comment by sadeghs** [comment]
If it's not in your solution then it's probably in your dependencies. If you can search your deps, if not then it's not the end of the world, when you update your deps the warning should go away hopefully.

**Comment by thenineteen** [comment]
```
 maybe a year and a half ago we only had xlrd as a reader, so it was a non-issue. But we've since added openpyxl, pyxlsb, and odfpy as readers, I think without using machinery similar to the writer side for respecting options.
```

from 

https://github.com/pandas-dev/pandas/issues/34252

and

https://stackoverflow.com/questions/60288732/pandas-read-excel-returns-pendingdeprecationwarning
