### ISSUE TITLE
GUI support for inverse localising spread value (ILV) option

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#191]
related to pull #190 

Please can we have an option right under the `Granular` option in settings (tab indented) that states `Use Inverse Localising Spread Values`.

- By default this should be unticked. 

- the option to tick the box should only be possible and made available to the user, if Granular option is ticked. Concretely, if both Granular and ILV boxes are ticked, if user unticks the Granular option, the ILV option should become unticked too.

- If ticked, it should set `self.inverse_localising_values =True` after the initialisation of the class `Semiology` in the module `semiology.py`

**Comment by thenineteen** [comment]
the tool tip can read

"This option, when enabled, reduces the localising-values in the Semio2Brain database inversely proportional to the number of brain regions the semiology of interest localised to"

**Comment by fepegar** [comment]
Done, but I get an error:

```
Error retrieving semiology information from mega_analysis module. Details:

cannot convert the series to <class 'float'>

If you think this is a bug, please report this issue on the repository: https://github.com/thenineteen/Semiology-Visualisation-Tool/issues/new
```

Are there tests for that option?

**Comment by fepegar** [comment]
P.S.: please stop changing the indentation in `semiology.py`. Your editor is doing it when you save.

**Comment by thenineteen** [comment]
Thanks for implementing this in the GUI!

Can you clarify what gives you that error? At what point in the query: do all semiology queries guve that error or a specific case? 

I saved without formatting on semiology.py but maybe I accidentally habitually pressed ctrl+s at some point, apologies if there are formatting changes.

There are indeed tests for this here https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/master/tests/test_inverse_localising_values.py

**Comment by fepegar** [comment]
Sorry, I clicked on the new checkbox and queried Tonic - left.

**Comment by fepegar** [comment]
Easiest way to reproduce: `python -c "import mega_analysis; np = mega_analysis.Semiology('Tonic', symptoms_side=mega_analysis.semiology.Laterality.LEFT, dominant_hemisphere=mega_analysis.semiology.Laterality.LEFT, inverse_localising_values=True).get_num_datapoints_dict()`.

But this is a different issue, so I'll close this.
