### ISSUE TITLE
Need Coverage for tests

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#193]

**Comment by thenineteen** [comment]
pytest coverage 83%

**Comment by thenineteen** [comment]
coverage is 84% but not clear why the badge doesn't update

![image](https://user-images.githubusercontent.com/10786099/92297299-c83d7f00-ef35-11ea-8113-8c4d42af4c86.png)

**Comment by thenineteen** [comment]
any thoughts on how to update the badge? @fepegar @sadeghs

**Comment by sadeghs** [comment]
Looks like it may have been a lag since I can see 84% now 
![image](https://user-images.githubusercontent.com/67839407/92309671-6e719f00-ef9f-11ea-99e2-5373149af775.png)
If you still don't see it try Ctrl+F5 on your browser.

**Comment by thenineteen** [comment]
Thanks yes clearing my cache worked
