### ISSUE TITLE
How many GIF parcellations are included in the SVT visualisation?

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#203]
What is the total number of different GIF parcellations supported by our programme? per hemisphere and in total please

e.g. 80 per hemisphere = 160 in total.

I need this to calculate the naive baseline probability of a semiology to localise to a given brain region, as benchmark for summary forrest plots

**Comment by fepegar** [comment]
According to the color table generated by [NiftyWeb](http://niftyweb.cs.ucl.ac.uk/program.php?p=GIF), of which we have an adaptation [in this repo](https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/master/slicer/Resources/Color/BrainAnatomyLabelsV3_0.txt), there are 156 possible structures/parcels/segments (after discarding the first five).

That doesn't mean all are present in the parcellation/segmentation we are using. There is some information about this in my comments in #184.

The parcellation we are using seems to have 137 different structures, discarding the first five as before:

```python
In [1]: import numpy as np

In [2]: import nibabel as nib

In [3]: data = nib.load('slicer/Resources/Image/MNI_152_gif.nii.gz').get_data()

In [4]: len(np.unique(data[data > 16]))
Out[4]: 137
```

**Comment by thenineteen** [comment]
I get different numbers depending on the exact query, but some of these GIF parcellations must be ignored then if we only have 137:

The below gives 146
```
from mega_analysis import Semiology, Laterality

patient = Semiology('Tonic',
    symptoms_side=Laterality.LEFT,
    dominant_hemisphere=Laterality.LEFT,
    normalise_to_localising_values=False,  # default is False
)

patient.granular = False
patient.top_level_lobes = True
heatmap = patient.get_num_datapoints_dict()

n = 0
for k,v in heatmap.items():
    n += 1
print(n)
```



Additionally, there are 115 parcellations when I looked at marginal probabilities for each GIF, of which the following are zero:

39 | 40 | 41 | 42 | 72 | 73 | 74
-- | -- | -- | -- | -- | -- | --

leaving around 108 non-zero
