### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#27]

**Comment by fepegar** [comment]
I added a [config file](https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/master/.travis.yml) for [continuous integration with Travis CI](https://travis-ci.com/).

@thenineteen, can you sign in and add this repo?

**Comment by thenineteen** [comment]
I'm drawing a blank here at 3:20am. Please be more specific, I'm not sure what I need to do!

**Comment by fepegar** [comment]
Sorry. Can you go to https://travis-ci.com/, sign in with your GitHub account and follow the instructions to add this repository? That will trigger automatic testing after every push and every pull request, and results will be shown on the badge I added to the README.

**Comment by thenineteen** [comment]
what build testing does it do - generic or specific to the pytests? is it working now?

**Comment by fepegar** [comment]
It does whatever we specify in the config file:
https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/01b4c8133a5a5221b2681b9ae1c2b5a84164356b/.travis.yml#L7-L11

It seems to be working: https://travis-ci.org/github/thenineteen/Semiology-Visualisation-Tool

**Comment by fepegar** [comment]
Before modifying the Slicer GUI at all, we need to make sure the API is working fine in `mega_analysis`, so we'll need to add tests for any additional or advanced options.

**Comment by thenineteen** [comment]
I'll try and do one for "autoscopic" semiology - would be useful to have the text search enabled for this (low counts and can manually quality control)

**Comment by fepegar** [comment]
I already have one for a non-existing semiology term, but I was waiting for your response in #33.

**Comment by fepegar** [comment]
I'll close this as there are some useful unit tests already.
