### ISSUE TITLE
GetCategoryInTerminology: Failed to find category 'Tissue' in 3D Slicer

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#32]
I suspect this isn't anything to worry about, but just checking?

```
GetCategoryInTerminology: Failed to find category 'Tissue' in terminology 'Segmentation category and type - 3D Slicer General Anatomy list'


DeserializeTerminologyEntry: Failed to get terminology category
```

![image](https://user-images.githubusercontent.com/10786099/78174245-da7c3400-7450-11ea-875f-20a1a56945dc.png)

**Comment by fepegar** [comment]
It looks like it's nothing to do with our stuff, we don't need to worry about terminologies.
