### ISSUE TITLE
Create CSV to define which structures need symptoms side

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#34]
These are the list of semiology checkboxes which shouldn't have a Left or Right option. just **one** checkbox, either ticked or not:

```
Aphasia
Aphemia
Astatic
Atonic
Auditory
Autonomous-Vegetative
**Coprolalia**  - note also the correct spelling
Cough
Dacrystic
Dialeptic/LOA
Drinking
Dysphasia
Epigastric
Fear-Anxiety
Gelastic
Grimace
Ictal Pout
LOC
Non-Specific Aura
Olfactory-Gustatory
Oral Automatisms
Other Automatism
**Palilalia** - note correct spelling
Psychic
Spitting
Vestibular
Vocalisation
Whistling
```

These semiology checkboxes should have the option to have L, or R, or a separate checkbox for "neutral/BL"
```
Blink
Hypermotor
Hypomotor
Lower Limb Automatism
Myoclonic
Other Complex Motor
Upper Limb Automatism
Visual
Tonic-Clonic
```

These should be removed altogether:
```
Hippocampal Sclerosis
```

**Comment by fepegar** [comment]
The list of semiologies is automatically retrieved:
https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/9e4cf8ed14d3d7b5d377dd4600d7cd12e52c57d8/mega_analysis/scores.py#L52-L55

Whether the semiologies are lateralisable or not should also be specified in the YAML file, not here.

> "neutral/BL"

What is BL?

> `**Palilalia** - note correct spelling`

The YAML needs to be corrected:
https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/9e4cf8ed14d3d7b5d377dd4600d7cd12e52c57d8/resources/semiology_dictionary.yaml#L143

> These should be removed altogether

Can you remove it from the YAML then?

**Comment by thenineteen** [comment]
BL = bilateral

**Comment by thenineteen** [comment]
yaml updated

but the lateralisation shouldn't be determined in yaml file.

**Comment by fepegar** [comment]
> BL = bilateral
> yaml updated

Thanks.

> the lateralisation shouldn't be determined in yaml file.

It should be somewhere in the repository. In that case, I suggest a new YAML containing the lists above.

**Comment by thenineteen** [comment]
good idea

how do we do this to be consistent with the GUI?

**Comment by fepegar** [comment]
What about writing a data frame (CSV) like this:

Term | Left | Right | Neutral
:---: | :---: | :---: | :---:
Auditory | Yes | Yes | No
Aphasia | No | No | Yes
Blink | Yes | Yes | Yes

And then the GUI will read the CSV and look a bit like this:

Term | Left | Right | Neutral
:---: | :---: | :---: | :---:
Auditory | <ul><li>- [x] item1</li></ul> | <ul><li>- [x] item1</li></ul> | 
Aphasia |  |  | <ul><li>- [x] item1</li></ul>
Blink | <ul><li>- [x] item1</li></ul> | <ul><li>- [x] item1</li></ul> | <ul><li>- [x] item1</li></ul>

We would need to define rules for what is mutually exclusive or not, i.e. which options the user can choose simultaneously.

**Comment by thenineteen** [comment]
Yes

Only 1 option from R, L or neutral
