### ISSUE TITLE
GUI text box semiology search

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#35]
an option to use user text instead of checkboxes - defaulting *semiology_dict_path=None* and using taking the user text as *semiology_term*

**Comment by fepegar** [comment]
What's a term not present in the dictionary and still producing results?

**Comment by thenineteen** [comment]
the dictionary is a made up list of 50 or so symptoms and signs that can occur during a seizure. The literature can report any number of symptoms and signs in a patient with epilepsy. for example, one publication can mention autoscopic semiology - this is when someone feels they are outside of their own body and looking at themselves. This occurs in the data, but isn't captured in the more frequently occurring semiology dictionary.

**Comment by fepegar** [comment]
I see. However, a query for 'Autoscopic' returns `None`.

**Comment by thenineteen** [comment]
Did you turn of semio_dict yaml file?

**Comment by fepegar** [comment]
> Did you turn off semio_dict yaml file?

Yes, it happens here:

https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/070a06460792935e2bbb0b3d54eaf4c406e47027/mega_analysis/semiology.py#L111-L119

**Comment by fepegar** [comment]
If you think the result of "Autocoscopic" shouldn't be None, shall I ask a test for that?

**Comment by thenineteen** [comment]
It's because it doesn't have lateralisation, which is what my pull request is fixing

**Comment by fepegar** [comment]
What pull request?

**Comment by thenineteen** [comment]
oh gosh ages ago can't remember. how did you search autoscopic in slicer

**Comment by fepegar** [comment]
Not on Slicer. Look:

```python
from mega_analysis import Semiology, Laterality
s = Semiology('Autoscopic', Laterality.LEFT, Laterality.LEFT)
s.get_num_datapoints_dict()
```

```python-traceback
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-7-38752e574257> in <module>
----> 1 s.get_num_datapoints_dict()

~/git/Semiology-Visualisation-Tool/mega_analysis/semiology.py in get_num_datapoints_dict(self)
    163
    164     def get_num_datapoints_dict(self) -> Optional[dict]:
--> 165         query_lateralisation_result = self.query_lateralisation()
    166         if query_lateralisation_result is None:
    167             message = f'No results generated for semiology term "{self.term}"'

~/git/Semiology-Visualisation-Tool/mega_analysis/semiology.py in query_lateralisation(self)
    145             gif_lat_file,
    146             side_of_symptoms_signs=self.symptoms_side.value,
--> 147             pts_dominant_hemisphere_R_or_L=self.dominant_hemisphere.value,
    148         )
    149

~/git/Semiology-Visualisation-Tool/mega_analysis/crosstab/mega_analysis/QUERY_LATERALISATION.py in QUERY_LATERALISATION(inspect_result, df, map_df_dict, gif_lat_file, side_of_symptoms_signs, pts_dominant_hemisphere_R_or_L, normalise_lat_to_loc)
    255             gifs_not_lat = pd.concat([gifs_not_lat, row_nonlat_to_one_map], join='outer', sort=False)
    256     #now combine the lateralised and non-lateralised:
--> 257     all_combined_gifs = pd.concat([all_combined_gifs, gifs_not_lat], join='outer', sort=False)
    258
    259

UnboundLocalError: local variable 'all_combined_gifs' referenced before assignment
```

This happens because these lines are never reached:
https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/e9495917e2677a49a40a8fd86a621e66b113d48c/mega_analysis/crosstab/mega_analysis/QUERY_LATERALISATION.py#L224-L230

That can be because `no_rows` is `0` here:
https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/e9495917e2677a49a40a8fd86a621e66b113d48c/mega_analysis/crosstab/mega_analysis/QUERY_LATERALISATION.py#L115

Or because of the multiple `continue` statements in the loop. I'll let you do the rest of the debugging.

**Comment by thenineteen** [comment]
hmmm, the error seems to suggest this may be related to the reason dominance alone dones't lateralise #85

**Comment by fepegar** [comment]
This is all that happens under the hood:
https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/e9495917e2677a49a40a8fd86a621e66b113d48c/mega_analysis/semiology.py#L127-L148

where the global variables are defined here:
https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/e9495917e2677a49a40a8fd86a621e66b113d48c/mega_analysis/semiology.py#L33-L45

**Comment by thenineteen** [comment]
this issue remain unresolved

somehow the way you call the API isn't doing what we think it is

- [ ] 1. check could it be that it is still looking at semiology dictionary even though it shouldn't?
- [ ] 2. may be it isn't reading both columns of excel
- [ ] 3. maybe it is searching for the entire phrase and not doing regex properly
- [ ] 4. maybe brackets in regex break the regex


```
import mega_analysis
from mega_analysis import Semiology, Laterality

semiology = Semiology(
      'Aura (Autoscopic, Out of Body), Aura (Other)', Laterality.NEUTRAL, Laterality.NEUTRAL,
)
num_patients_dict = semiology.get_num_datapoints_dict()
print('Result:', num_patients_dict)
```



even when i substitute `Aura (Autoscopic, Out of Body), Aura (Other)` for `autoscopic` (which is exactly how it occurs in the excel file) it still doesn't find anything.

**Comment by thenineteen** [comment]
ok I've checked:


`semiology = Semiology(
      'Semio', Laterality.NEUTRAL, Laterality.NEUTRAL,
)` works

but 

`semiology = Semiology(
      '(Semio', Laterality.NEUTRAL, Laterality.NEUTRAL,
)`  breaks the code due to regex !!


```
Exception has occurred: error
missing ), unterminated subpattern at position 4
```

Need to fix this as it is a bug which means many other semiologies are being missed already including the semiologies we thought worked from the dictionary! Also explains why there were too few aphasias! And text search won't work without this being fixed either.

**Comment by thenineteen** [comment]
potential fixes:

1. the mega_analysis_df preprocessed to replace parentheses with nothing

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.replace.html


2. Would probably also need to remove any parenthesis the user types into the GUI text box e.g. using .strip() or .replace() or re.sub()

**Comment by fepegar** [comment]
You could also escape the parentheses, replacing `(` with `\(` and `)` with `\)`.

**Comment by thenineteen** [comment]
I'll make another issue for this.

**Comment by fepegar** [comment]
This is actually complex than I thought because I suppose a single edit box is not enough. The user might want to add multiple custom terms. Is that correct?

**Comment by thenineteen** [comment]
Yes

So solutions exist which may help a workaround as I had to do this for the semiology dictionary already:

1. If using the free text box, generate a a new (dummy) dictionary key for which each term the user enters is one of the values. Then user clicks on "query" and it runs just like it would when ticking a checbox currently would.

2. Use the QUERY_SEMIOLOGY_AND module in mega_analysis. In this case, each term the user enters is treated as a separate dictionary key, of which it is its own value. (I.e. a one value {key:value} for which the string of key==value is true) and the above module will be a workaround.

Either method would work

**Comment by fepegar** [comment]
I just meant it's hard to generate a dynamic GUI with an arbitrary number of text boxes, which is independent of how custom queries are processed by the Python module.

**Comment by fepegar** [comment]
Added in 2f9c059. Feel free to reopen if further work is needed.

**Comment by thenineteen** [comment]
great I'll check it out shortly
