### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '?'

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#48]
Querying `Head version` raises an error. This happens because there are question marks in the Excel file.

**Comment by fepegar** [comment]
This test should pass once this is fixed:
https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/8428ef7ff708fd371a0bb67f623c06df9540b916/tests/test_semiology.py#L78-L81

**Comment by thenineteen** [comment]
fixed with [fb7de2e](https://github.com/thenineteen/Semiology-Visualisation-Tool/commit/fb7de2e76f7699d033ff4680f6cf007e2240cad9) to master and developing further fixes in this [pull ](https://github.com/thenineteen/Semiology-Visualisation-Tool/pull/46)

**Comment by fepegar** [comment]
Can you create a separate PR for each fix instead?
