### ISSUE TITLE
Follow PEP8

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#50]
[PEP8](https://realpython.com/python-pep8/) helps for readability and reduces chance of errors (see https://github.com/thenineteen/Semiology-Visualisation-Tool/commit/38eef7a0c25268dd4b619503d03d6a708b1c25ad).

The library should be adapted to PEP8. For example, modules should be lower-case, constant (global) variables should be upper-case.

**Comment by thenineteen** [comment]
cool

close?

**Comment by fepegar** [comment]
Why close? This is still an open issue.
