### ISSUE TITLE
testing for impossible inputs needs to be removed

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#56]
you still have testing for impossible inputs, like aphasia on the left with neutral dominant hemisphere, which shouldn't even be allowed and won't be possible from the checkboxes. I removed these in the past and you reverted the changes. 

As even the master branch is failing, it has become a huge tangle of issues and failed testing, some of which seem based and different interpretations on what should actually be happening under the hood?

**Comment by fepegar** [comment]
> you still have testing for impossible inputs, like aphasia on the left with neutral dominant hemisphere, which shouldn't even be allowed and won't be possible from the checkboxes. I removed these in the past and you reverted the changes.

I'll remove the tests for impossible inputs. You didn't say why you removed them.

> As even the master branch is failing, it has become a huge tangle of issues and failed testing, some of which seem based and different interpretations on what should actually be happening under the hood?

I'm not sure what you mean. If it's not related to the tests you mention, you can create a new issue.

**Comment by fepegar** [comment]
Also, if they are impossible, shouldn't the package raise an error when being queried?

**Comment by fepegar** [comment]
Please let me know what  you think about this: https://github.com/thenineteen/Semiology-Visualisation-Tool/issues/56#issuecomment-610560205

**Comment by thenineteen** [comment]
erm, depends what you think the package does, or want it to do. 
if there are no checkboxes, why waste time giving errors that won't be utilised?

this is part our teething issues as we try to mould everything together including GUI
