### ISSUE TITLE
All "from x import *" must be removed

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#6]
See https://stackoverflow.com/questions/2386714/why-is-import-bad

**Comment by thenineteen** [comment]
the only one import * remaining is in `SemiologyVisualisation.py`

`from slicer.ScriptedLoadableModule import *`

**Comment by thenineteen** [comment]
I will close this now though as the reason this issue was opened was due to the multitude of import * in the mega analysis module which has now been resolved
