### ISSUE TITLE
GUI colour scale doesn't work for me

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#61]
![image](https://user-images.githubusercontent.com/10786099/78825401-d3689f00-79d7-11ea-8585-a9f46ee156d0.png)

**Comment by fepegar** [comment]
You need to update Slicer.

**Comment by thenineteen** [comment]
I tried, didn't work, I'm probably doing something wrong - can you send me the link you used? also do I have to uninstall current version of slicer?

**Comment by fepegar** [comment]
Yes, you need to uninstall the current version and install the latest preview version.

**Comment by fepegar** [comment]
Have you tried with the latest version? I saw that you're still using a version from March.

@neurokleos, can you see the colorbar?

**Comment by neurokleos** [comment]
Yes, of course, always did @fepegar - I think this is an old conversation and issue?

**Comment by fepegar** [comment]
I'm not sure what you mean. The colours were not visible for Ali, so it's still an open issue.

**Comment by neurokleos** [comment]
@fepegar @thenineteen Have you seen perhaps my editing of the intro page and suggestions for filters from last week?

**Comment by fepegar** [comment]
That's a different issue :) But I'll try to work on the SVT tomorrow afternoon and Monday.

**Comment by neurokleos** [comment]
the colourbar was never an issue for me - I though Ali fixed it by using the updated version, sorry

**Comment by neurokleos** [comment]
no rush for the other issue @fepegar

**Comment by thenineteen** [comment]
This works after reinstall. Thanks!
