### ISSUE TITLE
reading excel localisation columns seems incomplete

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#62]
anatomical_regions in group_columns.py:

```
def anatomical_regions(df):
    localisation_labels = df.columns[17:72]  

    return localisation_labels

```

seems like it should be:

```
def anatomical_regions(df):
    localisation_labels = df.columns[17:103]  # 17:72  # March excel updated to 17:103

    return localisation_labels

```
but this causes the modules to break when melting (melt_then_pivot_query). could be another high-level function calling the lateralisation or id_vars isn't updated, as can't seem to find the problem.

**Comment by fepegar** [comment]
I have no idea, I never touch the Excel columns/rows.

**Comment by thenineteen** [comment]
there are a lot of legacy issues such as having a double named mega_analysis folder and an unnecessary crosstab folder, but I won't change these for now. This resulted in me ignoring semiology_all_localisations.py which contains:

```
all_localisations

```



will create a pull request combining the following changes:
**semiology_all_localisations**
```
def all_localisations(localisation_columns="R:CZ"):
```

**group_columns.py**
```
def anatomical_regions(df):
    localisation_labels = df.columns[17:103]  # 17:72  # March excel updated to 17:103

    return localisation_labels
```

**Comment by thenineteen** [comment]
this seems to have been fixed in a previous merge,  Ihave double checked and vermis comes up as a region in the logging after running MEGA_ANALYSIS

```
THESE ARE THE REMOVED EMPTY LABELS:"#


```

**Comment by thenineteen** [comment]
related to #71 actually this was only fixed in the combo commits:

3684468 and
6ce476f
