### ISSUE TITLE
when querying Aphasia in slicer, it's as if only post-itcals are queried!

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#65]
checked manually and only searching for post-ictal results give the same output as the slicer logging: 

```
post-ictals: 	localising: 3
		        lateralising: 2 (DomH: 2)
```
This is highly unusual, as it suggests all data are dropped except for post-ictals. 

can you clarify here what is past on to exclusions.py and/or MEGA_ANALYSIS from your API? Specifically, what is excluded and what isn't, by default, when we click on Aphasia?

**Comment by thenineteen** [comment]
manual aphasia check:

```
loc: 11
lat: 2

post-ictals: 	loc: 3
		lat: 2 (DomH: 2)

ES: 	loc: 6
	lat: 2
sEEG: 	loc: 2
	lat: 1
concord:	loc: 1

all 3: 	loc: 1
post/op sEEG:	loc: 1
```

need test_fixtures on the df but also smaller df elements

**Comment by fepegar** [comment]
> can you clarify here what is past on to exclusions.py and/or MEGA_ANALYSIS from your API? Specifically, what is excluded and what isn't, by default, when we click on Aphasia?

Everything is default, just whatever kwargs you have in your functions. `MEGA_ANALYSIS` is called just once in `semiology.py`.

It'd be useful if, every time you show an output, you could also share the code you used to generate it.

**Comment by thenineteen** [comment]
![image](https://user-images.githubusercontent.com/10786099/80433047-c14e9200-88ed-11ea-92ac-aac4510db27c.png)


this clearly shows (highlighted) that the MEGA_ANALYSIS default behaviour to exclude post_ictals isn't being called as such - as it should state postictals have been excluded

**Comment by thenineteen** [comment]
any update? ^

**Comment by fepegar** [comment]
What is exactly the problem? Do you have code to reproduce it?

**Comment by thenineteen** [comment]
the problem is described above, which part needs a code?

see the picture: this shows output of MEGA_ANALYSIS. under section1, where exclusions are applied, it says "no exclusions". 

this is section 1:

```
# 1. Exclusions
    if exclude_data:
        logging.debug('\n\n1. Excluding some data based on ground truths')
        if not kwargs:
            df = exclusions(df,
                POST_ictals=True,
                PET_hypermetabolism=True,
                SPECT_PET=False,
                CONCORDANCE=False)
        elif kwargs:
            df = exclusions(df,
                POST_ictals=kwargs['POST_ictals'],
                PET_hypermetabolism=kwargs['PET_hypermetabolism'],
                SPECT_PET=kwargs['SPECT_PET'],
                CONCORDANCE=kwargs['CONCORDANCE'])

        print('\ndf.shape after exclusions: ', df.shape)
    else:
        logging.debug('1. No Exclusions.')

```

**Comment by fepegar** [comment]
Fixed in https://github.com/thenineteen/Semiology-Visualisation-Tool/pull/84.
