### ISSUE TITLE
need to test reading excel localisation columns

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#71]
We need a test to ensure 

- inspect_result from QUERY_SEMIOLOGY(semiology_term=['Dialeptic/LOA']) has a column named "Cerebellum" and "Hemisphere"

- mega_analysis_df has a columns named "INSULA", "CEREBELLUM" and "Vermis"

related to issue #62 and draft pull #70

**Comment by fepegar** [comment]
So should we add this test after you've merged #70?

**Comment by thenineteen** [comment]
we should test it now, i think #70 is void

**Comment by fepegar** [comment]
Why do you want to test such specific things?

**Comment by thenineteen** [comment]
fixed in the combo commits:

3684468 and
6ce476f

in future, anatomical_regions() needs to be updated when new spreadsheet is uploaded as Gloria has added new non-localisation columns
