### ISSUE TITLE
PIPELINE SEQUENCE FIXTURES: need fixture(s) to test the outputs of pipelines on inspect_result (Q_S) and all_gifs (Q_L) remain the same 

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#74]
when code is modified, it may fix errors but in inadvertently change the outputs e.g. the numbers in the dataframes returned by the functions used for gif visualisation.

For a given Semiology and its Lateralisations, we need 2 or 3 unittests which compare the live output to their fixtures.

e.g. if i change the regex capturing groups, there can be unexpeccted failure to find certain terms which would only show up if these fixture tests fail

**Comment by fepegar** [comment]
Yeah makes sense. But they will need to be modified if the Excel is updated, right?

**Comment by thenineteen** [comment]
I was thinking we could have fixtures which are a static pickled df or csv df  - which could be trimmed versions or current version of the excel data. So when the excel is updated, from the other tests we would know if it is reading it ok. And from the assertions on the fixtures we would know they work as intended wrt data processing?

**Comment by fepegar** [comment]
Yes, but not serialized: https://github.com/thenineteen/Semiology-Visualisation-Tool/issues/17

**Comment by thenineteen** [comment]
fine if you don't like serialised we can use csv :-)

**Comment by thenineteen** [comment]
adding bug label to prioritise for myself

**Comment by thenineteen** [comment]
related to #94

**Comment by thenineteen** [comment]
much of this has been addressed in `test_dummy_data.py` (`TestDummyDataDummyDictionary`) and it in fact revealed bugs which may not have otherwise have been found if we just relied on testing for equality of DataFrames. 

therefore closing this in favour of #94
