### ISSUE TITLE
postcode localisation data prefilter

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#76]
background to this issue can be found at issue #75 

2. we need a dictionary or class or function, which is appended to and called right at the end of MEGA_ANALAYSIS.py initialisation (run only once as slicer loads), which compares all the granular data (e.g. planum polare) to its top level hierarchies (e.g. STG, Temporal) and compares the numbers. 

If there are e.g. 

```
2 for planum polare, and 3 for STG, and 4 for temporal:

then reduce STG to 1, temporal to 1 
(STG_new = STG_old - planum_polare)
(temporal_new = temporal_old - STG_old)

will get complicated due to the hierarchies, and I need help to plan how to code this @fepegar 
```

**Comment by fepegar** [comment]
I don't know what any of this means. We'll need to discuss on a TC.

**Comment by thenineteen** [comment]
lets keep a list or just go through the issues one by one in next meeting?

**Comment by fepegar** [comment]
Probably easiest to discuss this in a meeting.

**Comment by thenineteen** [comment]
This is done. I wish we had stuck to NOT including this very messy postcode system of data entry but I think it is now reversed as best as can be, given it is a non-invertible problem. Essentially, the new hierarchy_dictionaries and the Hierarchy class make the data granular using the 'max' hierarchy_reversal() method.

The current dictionaries work for the current data spreadsheet. When the most up to date when is uploaded, @neurokleos has added more collumns and so this will need to be rechecked.

**Comment by thenineteen** [comment]
oops I forgot. We need to actually call this hierarchy/postcode filter now - which ideally I think should be an extra checkbox option as in the image below:


concretely, the checkbox should be ticked by default, and this should run the extra code below:

`semiology.py` line 149 returns `inspect_result`. When the checkbox is ticked, the following extra bit of code should be run afterwards:

```
from mega_analysis.crosstab.hierarchy_class import Hierarchy

hierarchy_df = Hierarchy(inspect_result)
hierarchy_df.all_hierarchy_reversal()  # deafult max option
inspect_result_reversed = hierarchy_df.new_df
```

and the rest of the code can stay the same as long as  `inspect_result = inspect_result_reversed`



![granular option](https://user-images.githubusercontent.com/10786099/85780682-c9c01f00-b71c-11ea-9bab-f7b302107e4d.jpg)

**Comment by fepegar** [comment]
I'm not sure this should be under visualisation settings, as it actually changes the quantitative results of the query.

**Comment by thenineteen** [comment]
> I'm not sure this should be under visualisation settings, as it actually changes the quantitative results of the query.

I don't mind you can put it under advanced tab as in the GUI user freindly layour issue #109

**Comment by thenineteen** [comment]
`granular: bool = False,` in `semiology.py` line 92

I can't see a checkbox option for this yet and I need to set to True as default please

**Comment by fepegar** [comment]
> I can't see a checkbox option for this yet and I need it set to True as default please

It's under the Query tab for now, pull the repo and you'll see it there, checked by default. I'll change the default value for the kwarg.

**Comment by thenineteen** [comment]
for some reason I am now entirely unable to open 3D slicer - crashes when trying to load 3D slicer

**Comment by thenineteen** [comment]
sweet works now

hadn't looked for it under query

**Comment by fepegar** [comment]
Can we close this now?

**Comment by thenineteen** [comment]
yes works as intended! the failing tests are unrealted
