### ISSUE TITLE
update semiology laterality

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#81]
the following laterality options need updating for the checkboxes on slicer:

```
TONIC: should have L, R or OTHER
OTHER SIMPLE MOTOR: should have L, R or OTHER
ALL AUTOMATISMS: should have L, R or OTHER
```

```
ICTAL SPEECH: should only have OTHER
```

**Comment by fepegar** [comment]
You can modify the .txt files in https://github.com/thenineteen/Semiology-Visualisation-Tool/tree/master/resources
