### ISSUE TITLE
Add option to choose and show a GIF structure

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#82]
(From #75)

@thenineteen, @neurokleos, can you please explain what you would like to see? Or even better, shall we arrange a TC for this?

**Comment by fepegar** [comment]
Would you prefer the structures sorted by label number or alphabetical order?

**Comment by neurokleos** [comment]
Sorting GIFs by label number it would be great!

**Comment by thenineteen** [comment]
this would be ideal!! e.g. I want to know where the uncus is hiding in these gifs... I need to visualise the gifs. Thanks! I'm up for a MS Teams meeting anytime

**Comment by thenineteen** [comment]
It would be ideal to order it by lobe: as per the tabs in 

```
syst_review_single_table.xlsx 
```
which is in resources. 

e.g. tab "GIF TL" and "GIF FL"

![image](https://user-images.githubusercontent.com/10786099/81875859-33bfa300-9579-11ea-8e31-bdb37c72223a.png)

**Comment by thenineteen** [comment]
so it takes column A and makes options from the rows as a checkbox for us to visualise. the tab can be called the same thing as the tab name , in ^case "GIF TL"

**Comment by fepegar** [comment]
Not by label number then?

**Comment by thenineteen** [comment]
first categorised by the sheetname in excel, then within the sheet ordered by label number - as above. I hope that makes sense

**Comment by fepegar** [comment]
If you write a function that reads the table and returns the mapping you'd like to use, I'll adapt the GUI.

**Comment by neurokleos** [comment]
The main issue is that GIFs are granular in nature, so we don't have macro-regions like lobes for example. Ideally we should have Temporal, Parietal, Occipital, Frontal, lobe etc, that atm are not present as stand-alone GIFs

**Comment by thenineteen** [comment]
I don't think that's the main issue @neurokleos .

The main issue is calibrating the excel sheet GIF mappings, which are granular in nature.

**Comment by fepegar** [comment]
Ali, do you think you can write a function that reads the Excel and returns a dictionary with the mapping you'd like? E.g.

```python
lobes_mapping = {
    'TL': (142, 143, 144, 145),
    'OL': (78, 79, 80, 81, 82, 83),
}
```

**Comment by thenineteen** [comment]
done

see the recent merge,
specifically `gif_lobes_from_excel_sheets()` which returns the lobes_mapping you requested

**Comment by fepegar** [comment]
`gif_lobes_from_excel_sheets` doesn't work. I added a test to help you.

I also removed all the Python files from `resources`. Please stick to pull requests so that these things don't happen.

**Comment by fepegar** [comment]
Also, you might want to use this to read the different Excel sheets: https://stackoverflow.com/a/26521726/3956024

**Comment by fepegar** [comment]
Also, is there a way to not read the Excel file again and again? For example this: https://stackoverflow.com/a/26521726/3956024

**Comment by thenineteen** [comment]
you've added a test which fails the build. This isn't helpful. Why not make a pull request so we can work on the fix before merging?

**Comment by fepegar** [comment]
The test fails because the function doesn't work. You can open a PR and one the tests are successful, that might mean that the function works (or at least it's returning a dictionary).

**Comment by thenineteen** [comment]
YOU DELETED FUNCTIONS BECAUSE THEY WERE IN A FOLDER YOU DIDN'T WANT THEM TO BE IN. This makes life really difficult for the active pull request. There was a reason I factored those into functions. I need to maintain the functions related to the resources. I put them in the same folder so for maintenance in future, only one folder's files need to be looked at. You've just deleted these without commenting first or pull requesting. Unhelpful.

**Comment by thenineteen** [comment]
If you want them elsewhere, we can discuss and move them e.g. into crosstab. But please don't just delete them.

**Comment by thenineteen** [comment]
> The test fails because the function doesn't work. You can open a PR and one the tests are successful, that might mean that the function works (or at least it's returning a dictionary).

it's a minor type

**Comment by thenineteen** [comment]
I've moved these files from resources to crosstab

> `gif_lobes_from_excel_sheets` doesn't work. I added a test to help you.
> 
> I also removed all the Python files from `resources`. Please stick to pull requests so that these things don't happen.

**Comment by fepegar** [comment]
> YOU DELETED FUNCTIONS BECAUSE THEY WERE IN A FOLDER YOU DIDN'T WANT THEM TO BE IN.

There's no need to talk like this, let's calm down.

> This makes life really difficult for the active pull request.

You can always rebase, but ok I'll PR next time.

> If you want them elsewhere, we can discuss and move them e.g. into crosstab. 

I actually moved them to `semiology.py`.

If you prefer, I'll just stop working on `mega_analysis` at all. I'll add the working features to Slicer and you'll have full responsibility about whether they work or not. This would make my life much easier.

**Comment by thenineteen** [comment]
I'm adding your new test and once I make it work, I'll commit to the pull #96 
then I'll work on resolving the conflicts with master.
Should then be ready to be pulled

**Comment by thenineteen** [comment]
Am I right in thinking this has been done? Because I can't see it. I can see the individual gif parcellation under Segmentations (only after running SVT and a query on 3D Slicer), but I can't see them grouped by lobe.
It would be VERY useful for @neurokleos and I to calibrate the mappings?

**Comment by fepegar** [comment]
Ok I'll work on this soon.

**Comment by fepegar** [comment]
Added in 1a7e0fa.

<img width="1280" alt="Screen Shot 2020-07-29 at 16 32 55" src="https://user-images.githubusercontent.com/12688084/88820435-3b2a3c00-d1b9-11ea-8285-6d85ace020fc.png">
