### ISSUE TITLE
GUI needs to be defined

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#9]
It must be consistent with the `mega_analysis` package API.

**Comment by thenineteen** [comment]
Please explain in more detail ?

**Comment by fepegar** [comment]
The Slicer graphical user interface (GUI) depends on what we want the user to be able to input into the system. Whatever can be specified in the GUI must be compatible with the `mega_analysis` API. The output of `mega_analysis` should be a data frame with shape `(num_semiology_terms, num_structures)`, and the way they are combined will be handled by Slicer. Is that correct?

Once there's a single branch and there are no conflicting issues, we can maybe have some docs to know what every single function does, and how they need to be called. We should also have some unit tests.

**Comment by thenineteen** [comment]
yes unit tests using the pickled dataframes on my to do list after I can open slicer and get it to work.

**Comment by fepegar** [comment]
Closing as there are issues about this already.
