### ISSUE TITLE
package name is not PEP8

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#92]
"Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged."

- https://www.python.org/dev/peps/pep-0008/#package-and-module-names

It is possible my pytest doesn't work due to this irregularity in the python package name.

output of my python test log:
```
ERROR collecting tests/test_exclusions.py __________________
ImportError while importing test module 'C:\Users\ali_m\AnacondaProjects\PhD\Semiology-Visualisation-Tool\tests\test_exclusions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_exclusions.py:2: in <module>
    from mega_analysis.semiology import mega_analysis_df
E   ModuleNotFoundError: No module named 'mega_analysis'
```

**Comment by thenineteen** [comment]
I propose

1. 1. rename repo to "SemiologyVisualisationTool"
2. we use the command

`$ git remote set-url origin new_url
`
https://help.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by thenineteen** [comment]
agree?

**Comment by fepegar** [comment]
The Python package name is `mega_analysis`, it has nothing to do with the name of the repo. It is a valid name, like [`face_recognition`](https://github.com/ageitgey/face_recognition). I suggest you try `pytest` on a toy repo.
