### ISSUE TITLE
Parenthesis in regex break regex

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#95]
ok I've checked:

`semiology = Semiology(
      'Semio', Laterality.NEUTRAL, Laterality.NEUTRAL,
)` works

but 

`semiology = Semiology(
      '(Semio', Laterality.NEUTRAL, Laterality.NEUTRAL,
)`  breaks the code due to regex !!

```
Exception has occurred: error
missing ), unterminated subpattern at position 4
```

Need to fix this as it is a bug which means many other semiologies are being missed already including the semiologies we thought worked from the dictionary! Also explains why there were too few aphasias! And text search won't work without this being fixed either.

_Originally posted by @thenineteen in https://github.com/thenineteen/Semiology-Visualisation-Tool/issues/35#issuecomment-633797972_

**Comment by thenineteen** [comment]
potential fixes:

the mega_analysis_df preprocessed to replace parentheses with nothing
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.replace.html

Would probably also need to remove any parenthesis the user types into the GUI text box e.g. using .strip() or .replace() or re.sub()

**Comment by thenineteen** [comment]
You could also escape the parentheses, replacing `(` with `\(` and `)` with `\)`.

_Originally posted by @fepegar in https://github.com/thenineteen/Semiology-Visualisation-Tool/issues/35#issuecomment-633858679_

**Comment by thenineteen** [comment]
Once this is solved,  the solution for #35 will work better

**Comment by thenineteen** [comment]
actually this is not an issue. As long as the use doesn't insert parentheses and is aware the GUI text box is a regex search. It doesn't break anything. parentheses in the actual database don't break this. Closing issue.

**Comment by fepegar** [comment]
I don't think it's safe to assume that users will know what a regex is.

**Comment by thenineteen** [comment]
it is safe to assume they won't search for anything but words containing the english alphabet though
I tried "aura" and other new semiologies, works fine and takes care of ignoring case anyway

**Comment by fepegar** [comment]
I agree. But isn't it easy to just get rid of parentheses in the input term, just in case?

**Comment by thenineteen** [comment]
Not really because currently the inout term from the semiology_dict yaml is treated the same as the GUI text box, and the former needs some regex e.g negative lookbehinds which include parentheses
