### ISSUE TITLE
need to update test exclusions

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#97]
some exclusions aren't imported in the test

**Comment by fepegar** [comment]
Which exclusions? Which test?

**Comment by thenineteen** [comment]
https://github.com/thenineteen/Semiology-Visualisation-Tool/blob/master/tests/test_exclusions.py

Spontaneous 
Paediatric 
Postictal

**Comment by fepegar** [comment]
Can you add them?
