### ISSUE TITLE
DataFrame datatypes need checking and casting

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#98]
use .astype('int32') for the localising and lateralising datapoints in MEGA_ANALYSIS

ensuring no decimals by accident

**Comment by fepegar** [comment]
You might want `uint16` instead.

**Comment by thenineteen** [comment]
even though uint16 may not be  CLS-compliant? https://stackoverflow.com/questions/1828575/why-should-i-write-cls-compliant-code

**Comment by fepegar** [comment]
Yes.

**Comment by thenineteen** [comment]
uint16 and int16/32 do not work for pandas casting

even with `df[['Localising', 'Lateralising']].fillna(0, inplace=True)`

therefore changed to `Int32` in 8395a5916a535106096a63056498bcec135e43b2

see e.g. https://stackoverflow.com/questions/11548005/numpy-or-pandas-keeping-array-type-as-integer-while-having-a-nan-value
