### ISSUE TITLE
Why is Laterality Class sharaed for patient and semiology?

### ISSUE THREAD

**Issue by thenineteen** [thenineteen/Semiology-Visualisation-Tool#99]
Intuitively it seems that a patient with a particular semiology should have two different lateralities:

Currently we have:
`
patient = Semiology('Aphasia', Laterality.NEUTRAL, Laterality.NEUTRAL)
`

We should have:
```
patient = PatientClass()
patient.dominance = Laterality.LEFT
patient.Semiology = 'Aphasia'

patient.Semiology.Lat = Laterality.NEUTRAL  
# this semiology lat would be automatic from the check of the txt file with possible lateralities, within the __init__ maybe




```

This isn't purely for semantics, I think it will be very useful as SVT expands: e.g. 
when considering e.g. postictal exclusions, these apply at the semiology level
Whereas e.g. paediatric exclusions, these apply at the patient level

**Comment by fepegar** [comment]
I think this is not necessary, we can call all the semiologies with the same dominance. Why change this if it's working well?
